### ISSUE TITLE
Release version 2.1.0

### ISSUE THREAD

**Issue by jeffpaul** [10up/wpsnapshots#79]
This issue is for tracking changes for the 2.1.0 release.  Target release date: **TBD**.

### Pre-release steps
- [x] Complete review of PR #41, resolve issues/merge ...or... punt to next release
- [x] Complete review of PR #57, resolve issues/merge ...or... punt to next release
- [ ] Complete review of PR #78, resolve issues/merge ...or... punt to next release

### Release steps
- [x] Branch: Starting from `develop`, cut a release branch named `release/2.1.0` for your changes.
- [x] Version bump: Bump the version number in `src/bootstrap.php` if it does not already reflect the version being released.
- [x] Changelog: Add/update the changelog in `CHANGELOG.md`.
- [x] Props: Update `CREDITS.md` file with any new contributors, confirm maintainers are accurate
- [x] Readme updates: Make any other readme changes as necessary in `README.md`.
- [ ] Merge: Make a non-fast-forward merge from your release branch to `develop` (or merge the pull request), then do the same for `develop` into `master` (`git checkout master && git merge --no-ff develop`). `master` contains the stable development version.
- [ ] Push: Push your trunk branch to GitHub (e.g. `git push origin master`).
- [ ] [Wait for build](https://xkcd.com/303/): Head to the [Actions](https://github.com/10up/wpsnapshots/actions) tab in the repo and wait for it to finish if it hasn't already. If it doesn't succeed, figure out why and start over.
- [ ] Check the build: Check out the `master` branch and test for functionality locally.
- [x] Release: Create a [new release](https://github.com/10up/wpsnapshots/releases/new), naming the tag and the release with the new version number, and targeting the `master` branch.  Paste the changelog from `CHANGELOG.md` into the body of the release and include a link to the closed issues on the [milestone](https://github.com/10up/wpsnapshots/milestone/5?closed=1).  The release should now appear under [releases](https://github.com/10up/wpsnapshots/releases).
- [x] Close milestone: Edit the [milestone](https://github.com/10up/wpsnapshots/milestone/5) with release date (in the `Due date (optional)` field) and link to GitHub release (in the `Description field`), then close the milestone.
- [x] Punt incomplete items: If any open issues or PRs which were milestoned for `2.1.0` do not make it into the release, update their milestone to `2.2.0` or `Future Release`.
